jobs:
  - script: >
      folder('VCS')
  - script: >
      pipelineJob('VCS/INFRA') {
            parameters {
                stringParam("GOAL", "plan", "plan/apply/cleanup")
            }        
            definition {
              cpsScm {
                  scriptPath 'HARRY/dev/CD/Jenkinsfile-infra'
                  lightweight true
                  scm {
                    git {
                        remote { 
                            url 'https://github.com/anouarharrou/Infra-as-code.git' 
                            credentials('github')
                        }
                        branch '*/master'
                        extensions {}
                    }
                  }
            }
          }
      }

  - script: >
      pipelineJob('VCS/DEPLOY_APPLI') {    
            definition {
              cpsScm {
                  scriptPath 'HARRY/dev/CD/Jenkinsfile-appli'
                  lightweight true
                  scm {
                    git {
                        remote { 
                            url 'https://github.com/anouarharrou/Infra-as-code.git' 
                            credentials('github')
                        }
                        branch '*/master'
                        extensions {}
                    }
                  }
            }
          }
      }
      
  - script: >
      pipelineJob('VCS/DEPLOY_WEB') {   
            definition {
              cpsScm {
                  scriptPath 'HARRY/dev/CD/Jenkinsfile-web'
                  lightweight true
                  scm {
                    git {
                        remote { 
                            url 'https://github.com/anouarharrou/Infra-as-code.git' 
                            credentials('github')
                        }
                        branch '*/master'
                        extensions {}
                    }
                  }
            }
          }
      }      

    # second folder  
  - script: >
      folder('KUBE')
  - script: >
      pipelineJob('KUBE/INFRA') {
            parameters {
                stringParam("GOAL", "plan", "plan/apply/cleanup")
            }        
            definition {
              cpsScm {
                  scriptPath 'HARRY/dev/CD/Jenkinsfile-infra'
                  lightweight true
                  scm {
                    git {
                        remote { 
                            url 'https://github.com/anouarharrou/Infra-as-code.git' 
                            credentials('github')
                        }
                        branch '*/master'
                        extensions {}
                    }
                  }
            }
          }
      }

  - script: >
      pipelineJob('KUBE/DEPLOY_APPLI') {    
            definition {
              cpsScm {
                  scriptPath 'HARRY/dev/CD/Jenkinsfile-appli'
                  lightweight true
                  scm {
                    git {
                        remote { 
                            url 'https://github.com/anouarharrou/Infra-as-code.git' 
                            credentials('github')
                        }
                        branch '*/master'
                        extensions {}
                    }
                  }
            }
          }
      }
      
  - script: >
      pipelineJob('KUBE/DEPLOY_WEB') {   
            definition {
              cpsScm {
                  scriptPath 'HARRY/dev/CD/Jenkinsfile-web'
                  lightweight true
                  scm {
                    git {
                        remote { 
                            url 'https://github.com/anouarharrou/Infra-as-code.git' 
                            credentials('github')
                        }
                        branch '*/master'
                        extensions {}
                    }
                  }
            }
          }
      }      
