---
- name: Download ASP.NET MVC 4
  win_get_url:
    url: "{{ asp_net_mvc_4_url }}"
    dest: D:\Applis\

- name: Create OCRE folder
  win_file:
    path: "{{ ocre_dir }}"
    state: directory

- name: Download Web Server configuration
  win_get_url:
    url: "{{ item.zip_url }}"
    dest: "{{ item.download_dir }}"
  loop: "{{ web_server_parameters }}"

- name: Unzip Web Server configuration
  win_unzip:
    src: "{{ item.download_dir }}"
    dest: "{{ ocre_dir }}\\{{ item.dest_dir }}"
    delete_archive: yes
  loop: "{{ web_server_parameters }}"